### ISSUE TITLE
See json in console logs, but no notifcation in gnome-shell

### ISSUE THREAD

**Issue by sweeze** [holylobster/nuntius-linux#1]
I'm running gnome-shell 3.14.3 on ubuntu vivid with bluez 5 installed from the ubuntu-desktop transitions ppa.  when running nuntius, I see notifications are recieved from my phone and outputted to the log in json format, but I never see any notificaiton in the shell.

**Comment by nacho** [comment]
Hi, thanks for the report. We had this issue, but it seems to be some kind of problem with gnome not getting the desktop file correctly registered. I am not completely sure what to say apart reboot the machine? :)

**Comment by sweeze** [comment]
ah i was trying to run it out of the src directory, make install and run it out of /usr/local seems to have fixed.  thanks!
