### ISSUE TITLE
support for ip/wlan/mdns

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [holylobster/nuntius-linux#12]
im using wlan with my phone, tablet and laptop, Bluetooth would basically be extra noise and a battery drain

**Comment by Algram** [comment]
+1

**Comment by flyingrub** [comment]
i think it's on a todo list :)
(mine in any case)

**Comment by Algram** [comment]
Is there any info we can get on this? How can we contribute to this being done?

**Comment by Kurtpenter** [comment]
Hi Algram,  You can start from this: https://github.com/holylobster/nuntius-android/wiki/TCP-Connection-Use-Case

Some work has been done on the Linux side too.  @nacho can you point to the right branch? 

—

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
