### ISSUE TITLE
 incorrect-fsf-address 

### ISSUE THREAD

**Issue by zaitor** [holylobster/nuntius-linux#13]
When building nuntius, rpmlint gives me a warning.

[   19s] nuntius.x86_64: W: incorrect-fsf-address /usr/share/doc/packages/nuntius/COPYING
[   19s] The Free Software Foundation address in this file seems to be outdated or
[   19s] misspelled.  Ask upstream to update the address, or if this is a license file,
[   19s] possibly the entire file with a new copy available from the FSF.

Thats pretty sad for a brand new package, please update to the latest version from FSF

**Comment by nacho** [comment]
Thanks for reporting
