### ISSUE TITLE
Not in the Fedora 21 repository list ?

### ISSUE THREAD

**Issue by onuralpszr** [holylobster/nuntius-linux#15]
I checked Fedora Package DB List and seems to be It's approved for F21 but I can't find in the list ? is there any reason ? (maybe still beta/testing or something like that) 

Thank you.

**Comment by nacho** [comment]
yeah, the packages can be found in koji but not yet on the repositoreis

**Comment by nacho** [comment]
For reference: http://koji.fedoraproject.org/koji/packageinfo?packageID=20047

**Comment by pbor** [comment]
I added a note to the readme file for now. Hopefully it will appear in the repo soon
