### ISSUE TITLE
can not be compiled

### ISSUE THREAD

**Issue by nrth3rnlb** [holylobster/nuntius-linux#32]
[aboettger:~/src/nuntius-linux] master\* ± make
make  all-recursive
make[1]: Entering directory '/home/aboettger/src/nuntius-linux'
Making all in po
make[2]: Entering directory '/home/aboettger/src/nuntius-linux/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/aboettger/src/nuntius-linux/po'
make[2]: Entering directory '/home/aboettger/src/nuntius-linux'
  VALAC    nuntius_vala.stamp
src/notificationsview.vala:135.30-135.35: error: Argument 1: Cannot pass ref argument to non-reference parameter
        buf.insert_with_tags(ref it, notification.title, -1, notification_tag, title_tag, null);
                             ^^^^^^
src/notificationsview.vala:138.34-138.39: error: Argument 1: Cannot pass ref argument to non-reference parameter
            buf.insert_with_tags(ref it, "\n\n", -1, notification_tag, null);
                                 ^^^^^^
src/notificationsview.vala:139.34-139.39: error: Argument 1: Cannot pass ref argument to non-reference parameter
            buf.insert_with_tags(ref it, notification.body, -1, notification_tag, null);
                                 ^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
Makefile:820: recipe for target 'nuntius_vala.stamp' failed
make[2]: **\* [nuntius_vala.stamp] Error 1
make[2]: Leaving directory '/home/aboettger/src/nuntius-linux'
Makefile:915: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/aboettger/src/nuntius-linux'
Makefile:504: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by nacho** [comment]
hi @aboettger you need a newer vala to compile it

**Comment by cellscape** [comment]
What exact version is supported? I tried with 0.26 but get the same error. Can minimal version be reflected in configure.ac?

**Comment by nacho** [comment]
@cellscape what error do you get with 0.26?

**Comment by cellscape** [comment]
```
src/notificationsview.vala:135.30-135.35: error: Argument 1: Cannot pass ref argument to non-reference parameter
        buf.insert_with_tags(ref it, notification.title, -1, notification_tag, title_tag, null);
                             ^^^^^^
src/notificationsview.vala:138.34-138.39: error: Argument 1: Cannot pass ref argument to non-reference parameter
            buf.insert_with_tags(ref it, "\n\n", -1, notification_tag, null);
                                 ^^^^^^
src/notificationsview.vala:139.34-139.39: error: Argument 1: Cannot pass ref argument to non-reference parameter
            buf.insert_with_tags(ref it, notification.body, -1, notification_tag, null);
                                 ^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
```

I don't know vala at all, but looking at gtk3 vala api, insert_with_tags indeed doesn't accept ref iterator, but simple insert does. Could this be a reason?

http://www.valadoc.org/#!api=gtk+-3.0/Gtk.TextBuffer.insert
http://www.valadoc.org/#!api=gtk+-3.0/Gtk.TextBuffer.insert_with_tags

**Comment by nacho** [comment]
It does https://git.gnome.org/browse/vala/tree/vapi/gtk+-3.0.vapi#n5295
Now  we just need to figure out when that changed and ifdef in relation to that

**Comment by nacho** [comment]
It seems it was added in a9a11d23aab730aa67a8be7d0fbc92e4d94beab9 so 0.27.1

**Comment by nacho** [comment]
Pushed a fix, can you test that it works?

**Comment by cellscape** [comment]
Works like a charm, thanks a lot for quick fix!

**Comment by nacho** [comment]
Closing then. Thanks for testing.
