### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by patricklibert** [holylobster/nuntius-linux#34]
Linux Mint 17.1 Cinnamon. The latest Valac 0.28 compiler.
No error with autogen....

make[2]: Entering directory `/home/redman/Downloads/nuntius/nuntius-linux-master'
  VALAC    nuntius_vala.stamp
  CC       application.o
src/application.c:2173:13: warning: ‘nuntius_application_handle_managed_objects_finish’ defined but not used [-Wunused-function]
 static void nuntius_application_handle_managed_objects_finish (NuntiusApplication* self, GAsyncResult* _res_) {
             ^
  CC       appslistpanel.o
  CC       appslist.o
  CC       connection.o
  CC       notification.o
  CC       notificationapp.o
  CC       notificationsview.o
src/notificationsview.c:78:76: error: unknown type name ‘GtkTextViewLayer’
 static void nuntius_notifications_view_real_draw_layer (GtkTextView* base, GtkTextViewLayer layer, cairo_t* cr);
                                                                            ^
src/notificationsview.c:95:76: error: unknown type name ‘GtkTextViewLayer’
 static void nuntius_notifications_view_real_draw_layer (GtkTextView* base, GtkTextViewLayer layer, cairo_t* cr) {
                                                                            ^
src/notificationsview.c: In function ‘nuntius_notifications_view_class_init’:
src/notificationsview.c:496:30: error: ‘GtkTextViewClass’ has no member named ‘draw_layer’
  ((GtkTextViewClass *) klass)->draw_layer = nuntius_notifications_view_real_draw_layer;
                              ^
src/notificationsview.c:496:45: error: ‘nuntius_notifications_view_real_draw_layer’ undeclared (first use in this function)
  ((GtkTextViewClass *) klass)->draw_layer = nuntius_notifications_view_real_draw_layer;
                                             ^
src/notificationsview.c:496:45: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [notificationsview.o] Error 1
make[2]: Leaving directory`/home/redman/Downloads/nuntius/nuntius-linux-master'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/redman/Downloads/nuntius/nuntius-linux-master'
make: **\* [all] Error 2

**Comment by nacho** [comment]
Thanks for the report, the problem was that we were depending on the wrong version of gtk.

**Comment by flyingrub** [comment]
did you managed to build it ?
cause here i still have those two error 

```
Requested 'gtk+-3.0 >= 3.14.0' but version of GTK+ is 3.10.8
No package 'json-glib-1.0' found
```

**Comment by leolzbing521** [comment]
Yes ,with ubuntu cound't build. gtk can modify configure to 3.10.8 ,but json-glib-1.0 allways report no package found .

At 2015-04-19 01:58:30, "Ronan Nello" notifications@github.com wrote:

did you managed to build it ?
cause here i still have those two error

Requested 'gtk+-3.0 >= 3.14.0' but version of GTK+ is 3.10.8
No package 'json-glib-1.0' found

**Comment by flyingrub** [comment]
could you share the step you followed in order to build it without error then :) ?
